import { readFile, writeFile, mkdir, copyFile, rm } from 'node:fs/promises';
import { resolve, join } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const out = join(root, 'landing-dist');
const cfg = JSON.parse(await readFile(join(import.meta.dirname, 'config.json'), 'utf8'));
const base = cfg.baseUrl.replace(/\/$/, '');
if (base && !/^https:\/\/[^/]+$/.test(base)) throw Error('baseUrl must be an HTTPS origin');
for (const key of ['googlePlayUrl','appStoreUrl']) if (cfg[key] && !/^https:\/\//.test(cfg[key])) throw Error(`${key} must be HTTPS`);
const escape = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url = path => base + path;
const legalSource = await readFile(join(root, 'src/pages/PublicInfoPage.jsx'), 'utf8');
function legal(name) {
  const start = legalSource.indexOf(`function ${name}() {`);
  const end = legalSource.indexOf('\nexport default', start + 1);
  if (start < 0 || end < 0) throw Error(`Missing legal source ${name}`);
  const part = legalSource.slice(start, end);
  const match = part.match(/<section className="public-copy legal-copy">([\s\S]*?)<\/section>/);
  if (!match) throw Error(`Missing legal content ${name}`);
  return match[1].replace(/ target="_blank"/g, '').replace(/ rel="noreferrer"/g, '');
}
const nav = `<a class="brand" href="/" aria-label="DINCR, inicio"><img src="/favicon.svg" width="34" height="34" alt=""> DINCR</a><nav aria-label="Principal"><a href="/#funciona">Cómo funciona</a><a href="/precios/">Precios</a><a href="/seguridad/">Seguridad</a><a href="/soporte/">Soporte</a></nav>`;
const footer = `<footer><div class="wrap footer"><strong>DINCR © 2026</strong><div><a href="/descargar/">Descargar</a><a href="/precios/">Precios</a><a href="/privacidad/">Privacidad</a><a href="/terminos/">Términos</a><a href="/seguridad/">Seguridad</a><a href="/soporte/">Soporte</a><a href="/eliminar-cuenta/">Eliminar cuenta y datos</a></div></div></footer>`;
const description = 'DINCR ayuda a organizar ingresos, gastos, cuentas, deudas y estrategia financiera en Costa Rica.';
function layout(path, title, content, { noindex = false, desc = description, schema = false } = {}) {
  const canonical = base && path !== '/404/' ? `<link rel="canonical" href="${escape(url(path))}"><meta property="og:url" content="${escape(url(path))}">` : '';
  const ld = schema ? `<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:'DINCR',applicationCategory:'FinanceApplication',operatingSystem:'Android, iOS',description, ...(base ? {url:base} : {})}).replace(/</g,'\\u003c')}</script>` : '';
  return `<!doctype html><html lang="es-CR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} | DINCR</title><meta name="description" content="${escape(desc)}">${noindex || !base ? '<meta name="robots" content="noindex,follow">' : ''}${canonical}<meta property="og:type" content="website"><meta property="og:site_name" content="DINCR"><meta property="og:title" content="${escape(title)} | DINCR"><meta property="og:description" content="${escape(desc)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${escape(title)} | DINCR"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css">${ld}</head><body><a class="skip" href="#contenido">Saltar al contenido</a><header class="wrap top">${nav}</header><main id="contenido">${content}</main>${footer}</body></html>`;
}
const store = (label,key) => cfg[key] ? `<a class="button" href="${escape(cfg[key])}" rel="noopener noreferrer">${label}</a>` : `<span class="button disabled" aria-label="${label}: próximamente">${label} · Próximamente</span>`;
const downloads = `<div class="actions">${store('Google Play','googlePlayUrl')}${store('App Store','appStoreUrl')}</div>`;
const prices = `<div class="cards prices">${[['Free','free','Resumen, ingresos, gastos, deudas y metas.'],['Basic','basic','Presupuesto guiado, calendario, recurrentes y reportes.'],['VIP','vip','Estrategia dinámica, escenarios y automatización de Gmail con autorización.']].map(([name,key,features])=>`<article class="card ${key==='vip'?'featured':''}"><span class="eyebrow">${name}</span><h3>₡${cfg.candidatePricesCRC[key].toLocaleString('es-CR')}<small>/mes</small></h3><p>${features}</p></article>`).join('')}</div><p class="note">Precios candidatos de lanzamiento, pendientes de confirmación. La versión actual de la aplicación y sus términos indican VIP a ₡5.990/mes; no se aplica aquí el precio candidato.</p>`;
const faq = [
 ['¿Qué es DINCR?','Una aplicación móvil de finanzas personales para organizar información financiera y apoyar decisiones.'],
 ['¿Cómo funciona?','Podés ingresar información y, en funciones disponibles según el plan, autorizar integraciones. Revisá los movimientos detectados antes de incorporarlos.'],
 ['¿Por qué DINCR puede solicitar acceso a Gmail?','Para detectar notificaciones financieras y proponer movimientos cuando activás la automatización disponible en VIP. El acceso a Gmail se solicita con tu autorización.'],
 ['¿DINCR lee todos mis correos?','La integración usa permiso de lectura de Gmail para buscar mensajes relevantes. El alcance exacto del acceso y la política de conservación deben revisarse antes de la verificación OAuth.'],
 ['¿Puedo usar DINCR sin conectar Gmail?','Sí. Podés registrar y consultar información financiera sin conectar Gmail.'],
 ['¿DINCR puede mover mi dinero?','Las estrategias y cálculos son informativos. DINCR no ejecuta inversiones ni movimientos bancarios desde esta función.'],
 ['¿Cómo protege DINCR mis datos?','Consultá la política vigente de privacidad y la información de seguridad; evitamos prometer certificaciones no verificadas.'],
 ['¿Puedo eliminar mi cuenta y mis datos?','Podés solicitar la eliminación; consultá las condiciones y excepciones en la política de privacidad.'],
 ['¿Qué bancos son compatibles?','La lista pública validada está pendiente. La detección de notificaciones depende del formato recibido y no equivale a una conexión bancaria.'],
 ['¿Cuánto cuesta DINCR?','Free es gratuito. Basic figura a ₡2.990/mes y VIP a ₡5.990/mes en el producto actual; los precios candidatos de lanzamiento se muestran arriba y están pendientes de confirmación.']
].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('');
const home = `<section class="hero wrap"><div><span class="eyebrow">FINANZAS PERSONALES · COSTA RICA</span><h1>Tus finanzas, <em>organizadas automáticamente.</em></h1><p class="lead">DINCR te ayuda a organizar ingresos, gastos, cuentas, deudas y estrategia financiera con menos trabajo manual.</p>${downloads}</div><div class="phone" role="img" aria-label="Espacio reservado para una captura real de DINCR en un teléfono"><div class="phone-inner"><span>DINCR</span><strong>Tu panorama financiero</strong><p>Próximamente: captura real de la aplicación</p><div class="mock-line"></div><div class="mock-line short"></div></div></div></section><section class="band" id="funciona"><div class="wrap"><span class="eyebrow">UN PANORAMA MÁS CLARO</span><h2>Entendé dónde estás. Decidí qué sigue.</h2><div class="cards four">${[['Automatiza','Reduce el registro manual cuando activás integraciones disponibles.'],['Entiende','Organiza ingresos, gastos, cuentas, movimientos y deudas.'],['Planifica','Propone una estrategia basada en la información disponible.'],['Evoluciona','Permite revisar el progreso y ajustar el plan con información nueva.']].map(([h,p])=>`<article class="card"><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></div></section><section class="wrap section"><span class="eyebrow">ASÍ FUNCIONA</span><h2>Vos conservás el control.</h2><ol class="steps"><li>Conectás o ingresás información</li><li>DINCR organiza</li><li>Confirmás</li><li>Revisás tu situación actualizada</li></ol><p>Algunas automatizaciones utilizan información financiera que autorizás compartir con DINCR. La disponibilidad depende del plan y de las integraciones compatibles.</p></section><section class="band"><div class="wrap split"><div><span class="eyebrow">PRIVACIDAD</span><h2>Tus finanzas son tuyas.</h2><p>DINCR utiliza los datos de cuenta y la información financiera que ingresás o autorizás para organizar movimientos, calcular resúmenes y mostrar estrategias. Podés solicitar la eliminación de tu cuenta y datos según la política vigente.</p></div><div class="linklist"><a href="/privacidad/">Privacidad ↗</a><a href="/terminos/">Términos y condiciones ↗</a><a href="/seguridad/">Seguridad ↗</a><a href="/soporte/">Soporte ↗</a><a href="/eliminar-cuenta/">Eliminación de cuenta y datos ↗</a></div></div></section><section class="wrap section" id="planes"><span class="eyebrow">PLANES</span><h2>Un plan para cada etapa.</h2>${prices}<a class="text-link" href="/precios/">Ver detalle de planes →</a></section><section class="band"><div class="wrap"><span class="eyebrow">OPINIONES</span><h2>Historias reales, cuando estén disponibles.</h2><p>Las reseñas oficiales de Google Play y App Store aparecerán aquí cuando existan.</p></div></section><section class="wrap section"><span class="eyebrow">PREGUNTAS FRECUENTES</span><h2>Lo esencial, sin letra pequeña.</h2><div class="faqs">${faq}</div></section><section class="cta wrap"><h2>Tu siguiente paso empieza con claridad.</h2>${downloads}</section>`;
const pages = {
 '/': layout('/', 'Tus finanzas, organizadas automáticamente', home, {schema:true}),
 '/precios/': layout('/precios/', 'Planes y precios', `<section class="wrap section"><span class="eyebrow">PLANES</span><h1>Planes DINCR</h1>${prices}<p>Las diferencias se basan en las funciones enumeradas en el producto actual. Confirmá el precio vigente dentro de la aplicación antes de contratar.</p></section>`),
 '/privacidad/': layout('/privacidad/', 'Política de privacidad', `<article class="wrap section legal"><h1>Política de Privacidad</h1><p>Versión vigente 2026-09-16-v1. Texto existente en la aplicación.</p>${legal('PrivacyPage')}</article>`),
 '/terminos/': layout('/terminos/', 'Términos y condiciones', `<article class="wrap section legal"><h1>Términos y Condiciones</h1><p>Versión vigente 2026-09-16-v1. Texto existente en la aplicación.</p>${legal('TermsPage')}</article>`),
 '/seguridad/': layout('/seguridad/', 'Seguridad', `<section class="wrap section"><span class="eyebrow">SEGURIDAD</span><h1>Tus finanzas son tuyas.</h1><p>DINCR utiliza autenticación y controles de acceso descritos en su política de privacidad. Vos decidís qué información ingresás y qué integraciones autorizás. Ningún sistema es infalible.</p><p>Revisá <a href="/privacidad/">la política de privacidad</a> para conocer el tratamiento de datos. Para comunicar un problema, consultá <a href="/soporte/">soporte</a>.</p></section>`),
 '/soporte/': layout('/soporte/', 'Soporte', `<section class="wrap section"><h1>Soporte DINCR</h1>${cfg.supportEmail ? `<p>Escribinos a <a href="mailto:${escape(cfg.supportEmail)}">${escape(cfg.supportEmail)}</a>.</p>` : '<p>El canal público de soporte está pendiente de confirmación. Si ya usás la aplicación, podés contactar mediante la sección de Reportes.</p>'}</section>`, {noindex:!cfg.supportEmail}),
 '/eliminar-cuenta/': layout('/eliminar-cuenta/', 'Eliminar cuenta y datos', `<section class="wrap section"><h1>Eliminar cuenta y datos</h1><p>Podés solicitar la eliminación de tu cuenta y datos. La política de privacidad describe los plazos y las excepciones aplicables.</p><p>En la aplicación, abrí Perfil o Más → Ajustes de cuenta y plan → Eliminar cuenta, y confirmá la solicitud. Si no podés acceder, utilizá la opción de soporte de la aplicación para solicitar ayuda.</p>${cfg.supportEmail ? `<p>También podés escribir a <a href="mailto:${escape(cfg.supportEmail)}">${escape(cfg.supportEmail)}</a>.</p>` : '<p>El contacto público de soporte está pendiente de confirmación.</p>'}<a href="/privacidad/">Leer política de privacidad →</a></section>`),
 '/bancos-compatibles/': layout('/bancos-compatibles/', 'Bancos compatibles', `<section class="wrap section"><h1>Bancos compatibles</h1><p>La lista pública de instituciones y formatos compatibles está pendiente de validación. DINCR no implica conexión directa ni convenio con un banco por detectar una notificación financiera.</p></section>`, {noindex:true}),
 '/descargar/': layout('/descargar/', 'Descargar DINCR', `<section class="wrap section"><h1>DINCR para iPhone y Android</h1><p>Los enlaces oficiales de descarga aparecerán aquí cuando estén disponibles.</p>${downloads}</section>`, {noindex:!cfg.googlePlayUrl&&!cfg.appStoreUrl})
};
await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true});
for (const [path,html] of Object.entries(pages)) { const dir=join(out,path); await mkdir(dir,{recursive:true}); await writeFile(join(dir,'index.html'),html); }
// Cloudflare Pages treats a site without a root 404.html as an SPA. This is a static multipage site.
await writeFile(join(out,'404.html'),layout('/404/', 'Página no encontrada', '<section class="wrap section"><h1>Página no encontrada</h1><p>Revisá la dirección o volvé al <a href="/">inicio de DINCR</a>.</p></section>',{noindex:true}));
await copyFile(join(root,'public/favicon.svg'),join(out,'favicon.svg'));
await copyFile(join(import.meta.dirname,'style.css'),join(out,'style.css'));
await writeFile(join(out,'robots.txt'),`User-agent: *\n${base ? `Allow: /\nSitemap: ${base}/sitemap.xml` : 'Disallow: /'}\n`);
if (base) await writeFile(join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${Object.keys(pages).filter(x=>!['/bancos-compatibles/'].includes(x) && (cfg.supportEmail || x!='/soporte/') && (cfg.googlePlayUrl || cfg.appStoreUrl || x!='/descargar/')).map(x=>`<url><loc>${escape(url(x))}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${Object.keys(pages).length} static public routes in ${out}`);
