// English translation of the legal texts published on dincr.com (/terminos/, /privacidad/).
//
// The Spanish text in src/pages/PublicInfoPage.jsx is the one accepted in the app; this is its
// faithful translation for visitors whose language is not Spanish. `version` must equal the
// Spanish version: build.mjs refuses to build when the Spanish text gets a new version and this
// translation has not been updated, so the English page can never describe an older policy.
// Section structure, contacts and links mirror the Spanish text (checked by test:landing-i18n).

export const legalEn = {
  TermsPage: {
    version: '2026-09-23-v3',
    title: 'Terms and Conditions',
    html: `
      <h2>1. Acceptance and capacity</h2><p>By creating or using an account, the person confirms that they have read and accepted these terms and the Privacy Policy. They must be at least 18 years old and have the legal capacity to contract. If they do not agree, they must not use the service.</p>
      <h2>2. Purpose of the service</h2><p>DINCR helps record, organize, analyze and project financial information. Its calculations, alerts, simulations and content generated with automation or artificial intelligence are for guidance only and may contain errors.</p>
      <h2>3. Not professional advice</h2><p>The service is not a bank, financial institution, accountant, investment advisor, lawyer or tax advisor. It does not execute investments and does not guarantee savings, returns, the elimination of debts or financial results. Final decisions belong to the user, who must verify the information and seek professional advice when appropriate.</p>
      <h2>4. Account and security</h2><p>The user must provide accurate information, protect access to their account, keep their device secure and report any unauthorized access. They may not share accounts, impersonate other people, attempt to breach the system or use it for unlawful purposes.</p>
      <h2>5. Data entered and authorizations</h2><p>The user retains ownership of their data and authorizes its processing solely to provide, maintain, protect and improve the features they request. The user is responsible for having authorization when they add information about third parties.</p>
      <h2>6. Plans, promotion and payments</h2><p>The Free plan has no cost. Basic and VIP will be available free of charge until December 31, 2026. From January 1, 2027, their monthly launch prices are ₡2,990 and ₡4,990, respectively. The promotion does not generate automatic charges and does not oblige anyone to subscribe. To continue with a paid plan, the user will have to initiate and confirm a payment through the method available at that time.</p>
      <h2>7. Activation of paid plans</h2><p>Basic and VIP purchases are not yet enabled. When they become available, in-app purchases will be made through Google Play or the App Store, depending on the device, under the conditions shown before the purchase is confirmed. The current promotion does not start a subscription or generate an automatic charge.</p>
      <h2>8. Availability and changes</h2><p>The service may change, suspend features or experience interruptions due to maintenance, security, providers or causes beyond reasonable control. Material changes to prices or conditions will be announced before they apply and may require a new acceptance.</p>
      <h2>9. Intellectual property</h2><p>The software, design, brand, content and proprietary models belong to their respective owners. The account grants a personal, limited, revocable and non-transferable license to use the service; it does not permit copying, reselling, decompiling or improperly exploiting its components.</p>
      <h2>10. Suspension and closure</h2><p>An account may be suspended for fraud, abuse, breach of these terms, security risk or legal requirement. The user may stop using the service and request the deletion of their account and data, subject to information that must be retained to comply with legal obligations, resolve payments or defend against claims.</p>
      <h2>11. Liability</h2><p>The service is provided with reasonable care, but it is not guaranteed to be uninterrupted or completely free of errors. To the extent permitted by applicable law, no liability is accepted for financial decisions made exclusively on the basis of estimates or of incorrect data entered by the user. This clause does not limit consumers' non-waivable rights.</p>
      <h2>12. Governing law and contact</h2><p>These terms are interpreted in accordance with the laws of Costa Rica. Questions, requests or complaints may be sent through the Reports section or to <a href="mailto:soporte@dincr.com">soporte@dincr.com</a>. Every effort will be made to resolve any disagreement in good faith before turning to the competent authorities.</p>
    `,
  },
  PrivacyPage: {
    version: '2026-09-25-v4',
    title: 'Privacy Policy',
    html: `
      <h2>1. Controller</h2><p>The data controller is Kenneth Andrés Alvarado Obando, Costa Rica, developer and operator of DINCR. For questions about privacy and personal data, write to <a href="mailto:privacidad@dincr.com">privacidad@dincr.com</a>. For general help, write to <a href="mailto:soporte@dincr.com">soporte@dincr.com</a> or use Reports.</p>
      <h2>2. Data processed</h2><p>We may process identification and account data (name, email and technical identifiers); financial information entered by the user (income, expenses, balances, debts, goals and budgets); payment receipts and account statements; usage events, error diagnostics and basic device data; and, if the user connects an email account, the sender, subject, date and content of messages from supported financial senders.</p>
      <h2>3. Purposes</h2><p>The data is used to authenticate the account, provide financial features, calculate summaries and simulations, synchronize authorized information, validate subscriptions, provide support, prevent fraud, protect the service, diagnose failures and improve stability and experience. It is not sold or used for third-party advertising.</p>
      <h2>4. Basis for processing</h2><p>The processing necessary to provide the service is carried out with the user's informed consent and to perform the features the user requests. Certain evidence may be retained for security, compliance with obligations and the handling of claims. Consent to promotional communications, if offered, will be separate and optional.</p>
      <h2>5. Providers and transfers</h2><p>Authentication, database, hosting, mobile distribution, monitoring and email providers may be involved in operating the service, including Supabase (authentication and database), Render (hosting), Google (Gmail and, on Android, Firebase Analytics and Crashlytics for usage metrics and error diagnostics), Microsoft (Outlook) and PostHog (anonymous product analytics, without email address, name or financial data). DINCR does not use generative artificial intelligence providers to provide the service, and data obtained from Gmail and Outlook is never shared with artificial intelligence or analytics providers (see section 6). Providers receive only the information necessary for their function and may process it outside Costa Rica under their own protection measures and conditions.</p>
      <h2>6. Email integrations (Google and Microsoft)</h2>
      <p><strong>Access.</strong> Connecting an email account is optional and is initiated by the user. With the read-only permission of Gmail (<code>gmail.readonly</code>) or Outlook (<code>Mail.Read</code>), DINCR searches only for messages from supported financial senders (bank notifications, account statements and CCSS employer payroll statements, "órdenes patronales") and reads their sender, subject, date, content and PDF attachments. It does not read or store any other emails. From those messages it derives proposed transactions (date, description, amount, currency, bank and last four digits of the account or card), detected accounts and payroll data for calculating the aguinaldo (Costa Rica's year-end bonus). The full body of the emails and the PDF files are not stored.</p>
      <p><strong>Use.</strong> This data is used only for features visible to the user: proposing transactions that the user accepts, corrects or rejects, showing the user's banks and accounts, reconciling account statements and calculating the aguinaldo. DINCR does not send, modify or delete emails.</p>
      <p><strong>Transfer.</strong> Data obtained from Gmail and Outlook, raw or derived, is not sold, is not used for advertising, is not transferred to data brokers, is not used to assess creditworthiness or for lending decisions, is not sent to artificial intelligence services and is not used to develop, improve or train artificial intelligence or machine learning models. It is processed only by the providers that host the service (Supabase and Render) on DINCR's behalf. No person reads it, except with the user's consent, for security purposes or when required by law.</p>
      <p><strong>Protection.</strong> The authorization (refresh token) is stored encrypted in Supabase Vault and never reaches the app; data travels over encrypted connections and is separated by account.</p>
      <p><strong>Retention and deletion.</strong> The technical detail used to review a finding is deleted after 30 days, and the sender and subject of the email after 90 days, when there are no pending reviews. Transactions that the user confirms become part of their financial history until the user deletes them or deletes their account. When the user disconnects the email account or deletes their account, the authorization is deleted and, for Gmail, revoked with Google; deleting the account also deletes the derived data. The user can also revoke access from their Google account.</p>
      <p lang="en">DINCR's use and transfer of information received from Google APIs to any other app will adhere to the <a href="https://developers.google.com/terms/api-services-user-data-policy">Google API Services User Data Policy</a>, including the Limited Use requirements. The use of raw or derived user data received from Workspace APIs will adhere to the Google User Data Policy, including the Limited Use requirements. Google Workspace API data, raw or derived, is not transferred to OpenAI or other generative-AI providers and is not used to develop, improve, or train generalized AI/ML models.</p>
      <h2>7. Retention</h2><p>Data is retained while the account is active or while it is necessary to provide the service. After a deletion request, it will be deleted or anonymized within a reasonable period, except for records that must be retained temporarily for security, payments, backups, legal obligations or claims.</p>
      <h2>8. Security</h2><p>We apply authentication, separation of information by account, access controls, secure connections, audit logs and access limited to necessary providers. No system is infallible; in the event of a relevant incident, containment measures will be taken and it will be communicated when appropriate.</p>
      <h2>9. User rights</h2><p>The user can download a copy of their data and delete their account from the app, and request the rectification or updating of their data or withdraw their consent where applicable. The user can also disconnect integrations from the app or from the corresponding provider. Withdrawal does not affect processing already lawfully carried out and may prevent certain features from continuing.</p>
      <h2>10. Automated decisions</h2><p>Financial recommendations and classifications may be generated automatically from the available data, but they are informational and do not by themselves produce a binding banking, credit, employment or legal decision.</p>
      <h2>11. Minors and third parties</h2><p>The service is not directed at persons under 18 years of age. Data about third parties must not be entered without a legitimate basis or the corresponding authorization.</p>
      <h2>12. Changes</h2><p>If this policy changes materially, the new version will be shown and a renewed acceptance may be requested before the user continues to use the app.</p>
    `,
  },
};
