import { ChevronRight, Crown, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { getBasicDashboard, getFreeDashboard } from "../services/jarvisApi";

const money=(value)=>new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0}).format(Number(value)||0);
const trend=(value)=>`${Number(value)>=0?"+":""}${money(value)}`;

export default function Dashboard({user,plan="free",onNavigate}){
  const[data,setData]=useState(null),[error,setError]=useState("");
  const advanced=plan==="basic"||plan==="vip";
  useEffect(()=>{(advanced?getBasicDashboard():getFreeDashboard()).then(setData).catch((err)=>setError(err.message));},[advanced]);
  if(error)return <div className="panel error">{error}</div>;
  if(!data)return <div className="panel">Cargando resumen...</div>;
  const categories=data.categories||[],history=data.monthly_history||[],balance=data.balance??data.available_after_commitments;
  const maxCategory=Math.max(...categories.map((item)=>Number(item.amount)),1);
  const maxMonth=Math.max(...history.flatMap((item)=>[Number(item.income),Number(item.expenses)]),1);
  return <section className={`dashboard-plan dashboard-${plan}`}><div className="hero"><span>{advanced?"BASIC 01":"FREE 01"}</span><h1>{advanced?"Tu panorama financiero":"Tu resumen financiero"}</h1><p>Hola {user?.display_name||""} · {data.month}</p></div><div className="kpis"><div className="card"><small>Ingresos del mes</small><strong>{money(data.income)}</strong>{advanced&&<em>{trend(data.trends?.income)} vs anterior</em>}</div><div className="card"><small>Gastos del mes</small><strong>{money(data.expenses)}</strong>{advanced&&<em>{trend(data.trends?.expenses)} vs anterior</em>}</div><div className="card"><small>Balance</small><strong className={Number(balance)<0?"negative":""}>{money(balance)}</strong></div><div className="card"><small>Deuda pendiente</small><strong>{money(data.debt?.remaining??data.debt_balance)}</strong>{advanced&&<em>{data.debt?.progress||0}% pagado</em>}</div>{advanced&&<><div className="card"><small>Ahorro líquido</small><strong>{money(data.savings)}</strong></div><div className="card"><small>Metas</small><strong>{data.goals?.progress||0}%</strong><em>{data.goals?.active||0} activas</em></div></>}</div><div className="panel free-chart"><h3>Ingresos vs gastos · 6 meses</h3>{history.map((row)=><div className="free-chart-row" key={row.month}><small>{row.month.slice(5)}</small><span title={`Ingresos ${money(row.income)}`}><i className="income" style={{width:`${Number(row.income)/maxMonth*100}%`}}/></span><span title={`Gastos ${money(row.expenses)}`}><i className="expense" style={{width:`${Number(row.expenses)/maxMonth*100}%`}}/></span></div>)}<div className="chart-legend"><span>● Ingresos</span><span>● Gastos</span></div></div><div className="panel free-categories"><h3>Gastos por categoría</h3>{categories.length?categories.map((item)=><div key={item.category}><span>{item.category}</span><i><b style={{width:`${Number(item.amount)/maxCategory*100}%`}}/></i><strong>{money(item.amount)}</strong></div>):<p>Sin gastos registrados este mes.</p>}</div>{plan==="free"&&<button className="dashboard-plan-action free" onClick={()=>onNavigate?.("monthly")}><span><strong>Ver resumen mensual</strong><small>Detalle descriptivo, sin recomendaciones.</small></span><ChevronRight size={20}/></button>}{plan==="basic"&&<button className="dashboard-plan-action basic" onClick={()=>onNavigate?.("budget")}><Sparkles size={21}/><span><strong>Abrir presupuesto guiado</strong><small>Distribuí el ingreso disponible por categorías.</small></span><ChevronRight size={20}/></button>}{plan==="vip"&&<button className="dashboard-plan-action vip" onClick={()=>onNavigate?.("strategy")}><Crown size={21}/><span><strong>Abrir Dirección VIP</strong><small>Tu experiencia VIP incluye toda la base Basic.</small></span><ChevronRight size={20}/></button>}</section>;
}
