import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Copy, RefreshCw, WalletCards } from "lucide-react";
import { confirmFinancialReconciliation, getFinancialReconciliation } from "../services/jarvisApi";

const crc = (value) => `₡${Math.round(Number(value || 0)).toLocaleString("es-CR")}`;

export default function Reconciliation() {
  const [state, setState] = useState({ loading: true, data: null, error: "" });
  const load = async () => { setState((s) => ({ ...s, loading: true, error: "" })); try { setState({ loading: false, data: await getFinancialReconciliation(), error: "" }); } catch (e) { setState({ loading: false, data: null, error: e.message || "No pude conciliar las cuentas." }); } };
  useEffect(() => { load(); }, []);
  if (state.loading) return <section className="hud-panel">Comparando saldos y movimientos...</section>;
  if (state.error) return <section className="hud-panel strategy-warning">{state.error}</section>;
  const data = state.data || {}; const summary = data.summary || {};
  const confirm = async (item) => { const value = window.prompt(`Saldo real confirmado para ${item.account_name}:`, String(item.real_balance)); if (value === null) return; const amount = Number(value); if (!Number.isFinite(amount)) return window.alert("Ingresá un monto válido."); if (!window.confirm("Esto guardará un nuevo saldo base y marcará la cuenta como conciliada. ¿Confirmar?")) return; await confirmFinancialReconciliation(item.account_id, { real_balance: amount, note: "Confirmado desde Conciliación financiera." }); await load(); };
  return <section className="reconciliation-page"><div className="hud-panel reconciliation-hero"><div><span className="strategy-eyebrow">JARVIS 09 · CONTROL</span><h2>Conciliación financiera</h2><p>Comparamos lo que JARVIS espera con el saldo real. Nada se modifica sin tu confirmación.</p></div><button className="strategy-refresh-btn" onClick={load}><RefreshCw size={17}/> Revisar de nuevo</button><div className="reconciliation-kpis"><div><WalletCards/><span>Cuentas</span><strong>{summary.accounts || 0}</strong></div><div><AlertTriangle/><span>Por revisar</span><strong className={summary.needs_review ? "negative" : "positive"}>{summary.needs_review || 0}</strong></div><div><Copy/><span>Posibles duplicados</span><strong>{summary.possible_duplicates || 0}</strong></div></div></div>
    <div className="hud-panel"><div className="panel-heading"><div><span className="strategy-eyebrow">SALDOS</span><h3>Esperado vs. real</h3></div></div><div className="reconciliation-account-list">{(data.accounts || []).map((item) => <article className={`reconciliation-account ${item.status}`} key={item.account_id}><div className="reconciliation-account-copy"><strong>{item.account_name}</strong><small>{item.institution || "Sin institución"}{item.last4 ? ` · ****${item.last4}` : ""} · actualizado {item.balance_as_of ? String(item.balance_as_of).slice(0, 10) : "sin fecha"}</small></div><div><span>Esperado <b>{crc(item.expected_balance)}</b></span><span>Real <b>{crc(item.real_balance)}</b></span></div><strong className={item.status === "ok" ? "positive" : "negative"}>{item.difference > 0 ? "+" : ""}{crc(item.difference)}</strong>{item.status === "ok" ? <CheckCircle2 className="positive"/> : <button className="ghost-button" onClick={() => confirm(item)}>Confirmar saldo</button>}</article>)}</div></div>
    {(data.unlinked_transactions || []).length > 0 && <div className="hud-panel reconciliation-alert"><h3>Movimientos sin cuenta asignada</h3><p>Podrían ser gastos olvidados o importaciones pendientes de clasificar.</p>{data.unlinked_transactions.slice(0, 12).map((item) => <div className="reconciliation-line" key={item.id}><span>{item.transaction_date} · {item.description}</span><strong>{crc(item.amount)}</strong></div>)}</div>}
    {(data.possible_duplicates || []).length > 0 && <div className="hud-panel reconciliation-alert"><h3>Posibles duplicados</h3><p>JARVIS los muestra para revisión; no elimina ninguno.</p>{data.possible_duplicates.map((item) => <div className="reconciliation-line" key={`${item.transaction_date}-${item.description}`}><span>{item.transaction_date} · {item.description}</span><strong>{item.count} × {crc(item.amount)}</strong></div>)}</div>}
    <div className="hud-panel timeline-assumptions"><span className="strategy-eyebrow">REGLA DE SEGURIDAD</span><p>{data.note}</p></div>
  </section>;
}
