"""Response language for text generated by the backend (DINCR public app).

The app sends ``Accept-Language: es|en`` from the same device-language rule
it uses for its own copy. Only the public DINCR routes are localized; every
other route (DINCR Owner/JARVIS) keeps its Spanish copy. A missing, empty or
unsupported value falls back to Spanish, the language of every client that
predates this contract.

Localized text must be deterministic: the same rule produces the same numbers
and decision in both languages; only the words change.
"""
from __future__ import annotations

from contextlib import contextmanager
from contextvars import ContextVar, Token
from typing import Iterator

SUPPORTED_LANGUAGES = ("es", "en")
DEFAULT_LANGUAGE = "es"
LOCALIZED_PATH_PREFIXES = ("/user-product/", "/auth/", "/product-ops/")

_language: ContextVar[str] = ContextVar("dincr_response_language", default=DEFAULT_LANGUAGE)


def resolve_language(accept_language: str | None) -> str:
    """First language tag of the header when supported, otherwise Spanish."""
    first = str(accept_language or "").split(",", 1)[0].split(";", 1)[0].strip().lower()
    primary = first.split("-", 1)[0]
    return primary if primary in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def language_for_request(path: str, accept_language: str | None) -> str:
    if not str(path or "").startswith(LOCALIZED_PATH_PREFIXES):
        return DEFAULT_LANGUAGE
    return resolve_language(accept_language)


def set_language(language: str) -> Token:
    return _language.set(language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE)


def reset_language(token: Token) -> None:
    _language.reset(token)


def current_language() -> str:
    return _language.get()


@contextmanager
def use_language(language: str) -> Iterator[None]:
    """Run a block in a fixed language, e.g. canonical Spanish for persisted state."""
    token = set_language(language)
    try:
        yield
    finally:
        reset_language(token)


def tx(spanish: str, english: str) -> str:
    """Pick the copy for the current response language."""
    return english if _language.get() == "en" else spanish


def plural(count: float | int, singular: tuple[str, str], many: tuple[str, str]) -> str:
    """Localized noun for a count: plural(n, ("mes", "month"), ("meses", "months"))."""
    return tx(*(singular if abs(float(count or 0)) == 1 else many))
