"""Response language for text generated by the backend (DINCR public app).

The app sends ``Accept-Language: es|en`` from the same device-language rule
it uses for its own copy. Only the public DINCR routes are localized; every
other route (DINCR Owner/JARVIS) keeps its Spanish copy. A missing, empty or
unsupported value falls back to Spanish, the language of every client that
predates this contract.

Localized text must be deterministic: the same rule produces the same numbers
and decision in both languages; only the words change.
"""
from __future__ import annotations

from contextlib import contextmanager
from contextvars import ContextVar, Token
from typing import Iterator

SUPPORTED_LANGUAGES = ("es", "en")
DEFAULT_LANGUAGE = "es"
# Two separate questions:
# 1. Which routes follow Accept-Language? The routes the DINCR app calls.
LOCALIZED_PATH_PREFIXES = ("/user-product/", "/auth/", "/product-ops/")
# ...except Owner/admin operations mounted under those prefixes: always Spanish.
OWNER_PATH_PREFIXES = ("/product-ops/owner/", "/auth/allowed-users")
# 2. Which routes serve DINCR Users (neutral voice via voice())? Only the
#    Users product. /product-ops/ and /auth/ are shared operations/account
#    routes and never switch the Owner assistant voice off by themselves.
DINCR_USERS_PATH_PREFIXES = ("/user-product/",)

_language: ContextVar[str] = ContextVar("dincr_response_language", default=DEFAULT_LANGUAGE)
_dincr_users: ContextVar[bool] = ContextVar("dincr_users_request", default=False)


def resolve_language(accept_language: str | None) -> str:
    """First language tag of the header when supported, otherwise Spanish."""
    first = str(accept_language or "").split(",", 1)[0].split(";", 1)[0].strip().lower()
    primary = first.split("-", 1)[0]
    return primary if primary in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def _is_owner_path(path: str) -> bool:
    return str(path or "").startswith(OWNER_PATH_PREFIXES)


def language_for_request(path: str, accept_language: str | None) -> str:
    if _is_owner_path(path) or not str(path or "").startswith(LOCALIZED_PATH_PREFIXES):
        return DEFAULT_LANGUAGE
    return resolve_language(accept_language)


def is_dincr_users_path(path: str) -> bool:
    """True for DINCR Users routes, which must never carry the Owner voice."""
    return str(path or "").startswith(DINCR_USERS_PATH_PREFIXES) and not _is_owner_path(path)


def set_dincr_users(value: bool) -> Token:
    return _dincr_users.set(bool(value))


def reset_dincr_users(token: Token) -> None:
    _dincr_users.reset(token)


def set_language(language: str) -> Token:
    return _language.set(language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE)


def reset_language(token: Token) -> None:
    _language.reset(token)


def current_language() -> str:
    return _language.get()


@contextmanager
def use_language(language: str) -> Iterator[None]:
    """Run a block in a fixed language, e.g. canonical Spanish for persisted state."""
    token = set_language(language)
    try:
        yield
    finally:
        reset_language(token)


def tx(spanish: str, english: str) -> str:
    """Pick the copy for the current response language."""
    return english if _language.get() == "en" else spanish


def voice(owner: str, spanish: str, english: str) -> str:
    """Owner/JARVIS keeps its personal assistant voice; DINCR users get neutral copy.

    Shared engines serve both products. Outside the DINCR Users routes
    (DINCR_USERS_PATH_PREFIXES) the Owner text is returned unchanged.
    """
    return tx(spanish, english) if _dincr_users.get() else owner


def plural(count: float | int, singular: tuple[str, str], many: tuple[str, str]) -> str:
    """Localized noun for a count: plural(n, ("mes", "month"), ("meses", "months"))."""
    return tx(*(singular if abs(float(count or 0)) == 1 else many))
